import { connectionOptions } from "../src/lib/db/connection.mjs";
import { writeFile } from "node:fs/promises";
import pg from "pg";
import { requiredEnv } from "./env.mjs";

const client = new pg.Client(
  connectionOptions(requiredEnv("MIGRATION_DATABASE_URL")),
);
await client.connect();
try {
  const { rows: types } = await client.query(
    "select oid, typname, typtype, typelem from pg_type",
  );
  const byOid = new Map(types.map((t) => [t.oid, t]));
  const { rows: enums } =
    await client.query(`select t.typname, array_agg(e.enumlabel::text order by e.enumsortorder) labels
    from pg_type t join pg_enum e on e.enumtypid = t.oid join pg_namespace n on n.oid = t.typnamespace
    where n.nspname = 'public' group by t.typname order by t.typname`);
  const enumNames = new Set(enums.map((e) => e.typname));
  const { rows: columns } =
    await client.query(`select c.relname, c.relkind, a.attname, a.atttypid,
    a.attnotnull, (d.oid is not null or a.attidentity <> '') has_default
    from pg_class c join pg_namespace n on n.oid = c.relnamespace
    join pg_attribute a on a.attrelid = c.oid
    left join pg_attrdef d on d.adrelid = c.oid and d.adnum = a.attnum
    where n.nspname = 'public' and c.relkind in ('r', 'v') and a.attnum > 0 and not a.attisdropped
      and c.relname <> 'app_migrations' order by c.relname, a.attnum`);
  const tables = new Map();
  for (const c of columns) {
    if (!tables.has(c.relname)) tables.set(c.relname, []);
    tables.get(c.relname).push(c);
  }
  function tsType(oid) {
    const t = byOid.get(Number(oid));
    if (!t) throw new Error(`Unknown PostgreSQL type ${oid}`);
    if (t.typelem) return `(${tsType(t.typelem)})[]`;
    if (enumNames.has(t.typname))
      return `DbEnums[${JSON.stringify(t.typname)}]`;
    if (tables.has(t.typname))
      return `Selectable<Database[${JSON.stringify(t.typname)}]>`;
    if (
      ["int2", "int4", "int8", "numeric", "float4", "float8", "oid"].includes(
        t.typname,
      )
    )
      return "number";
    if (t.typname === "bool") return "boolean";
    if (["json", "jsonb"].includes(t.typname)) return "Json";
    if (t.typname === "void") return "undefined";
    if (["record", "trigger"].includes(t.typname)) return "unknown";
    return "string";
  }
  let source =
    "// Generated by npm run db:types from PostgreSQL. Do not edit.\n";
  source +=
    'import type { ColumnType, Generated, Selectable } from "kysely";\n';
  source +=
    "export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];\n\n";
  source +=
    "export interface DbEnums {\n" +
    enums
      .map(
        (e) => `  ${e.typname}: ${e.labels.map(JSON.stringify).join(" | ")};`,
      )
      .join("\n") +
    "\n}\n\n";
  source += "export interface Database {\n";
  for (const [name, cols] of tables) {
    source += `  ${name}: {\n`;
    for (const c of cols) {
      let type = tsType(c.atttypid) + (c.attnotnull ? "" : " | null");
      if (c.relkind === "v") type = `ColumnType<${type}, never, never>`;
      else if (c.has_default || !c.attnotnull) type = `Generated<${type}>`;
      source += `    ${c.attname}: ${type};\n`;
    }
    source += "  };\n";
  }
  source += "}\n\nexport interface DbFunctions {\n";
  const { rows: functions } =
    await client.query(`select p.proname, p.proargnames, p.proargmodes::text[] proargmodes,
    p.proallargtypes, p.proargtypes::oid[] input_types, p.pronargdefaults, p.prorettype, p.proretset
    from pg_proc p join pg_namespace n on n.oid = p.pronamespace
    where n.nspname = 'public' and p.prokind = 'f' order by p.proname`);
  for (const f of functions) {
    const input = f.input_types
      .map(
        (oid, i) =>
          `${f.proargnames?.[i] ?? `arg${i}`} ${i >= f.input_types.length - f.pronargdefaults ? "?" : ""}: ${tsType(oid)}`,
      )
      .join("; ");
    const output = f.proargmodes
      ?.map((mode, i) =>
        ["o", "t", "b"].includes(mode)
          ? `${f.proargnames[i]}: ${tsType(f.proallargtypes[i])}`
          : null,
      )
      .filter(Boolean);
    const result = output?.length
      ? `{ ${output.join("; ")} }`
      : tsType(f.prorettype);
    source += `  ${f.proname}: { Args: ${input ? `{ ${input} }` : "Record<string, never>"}; Returns: ${result}${f.proretset ? "[]" : ""} };\n`;
  }
  source += "}\n\nexport const setReturningFunctions = new Set<string>([\n";
  source +=
    functions
      .filter((f) => f.proretset)
      .map((f) => `  ${JSON.stringify(f.proname)},`)
      .join("\n") + "\n]);\n";
  await writeFile("src/types/database.ts", source);
  console.log(
    `Generated ${tables.size} tables/views and ${functions.length} SQL functions`,
  );
} finally {
  await client.end();
}
